/**
 * 
 * /home/tomas/workspace/mqtt-d/source/factory.d
 * 
 * Author:
 * Tomáš Chaloupka <chalucha@gmail.com>
 * 
 * Copyright (c) 2015 Tomáš Chaloupka
 * 
 * Boost Software License 1.0 (BSL-1.0)
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy
 * of the software and accompanying documentation covered by this license (the "Software") to use,
 * reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative
 * works of the Software, and to permit third-parties to whom the Software is furnished to do so,
 * all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license
 * grant, this restriction and the following disclaimer, must be included in all copies of the Software,
 * in whole or in part, and all derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
 * DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
module mqttd.serialization;

import std.string : format;
import std.range;
import std.typecons;

import mqttd.messages;
import mqttd.traits;
import mqttd.ranges;

debug import std.stdio;

/**
* Walk over all members of Mqtt packet, checks if member should be handled and calls defined callback for it
*/
private void processMembers(alias memberCallback, T)(ref T item) if (isMqttPacket!T)
{
    import std.typetuple;

    foreach(member; __traits(allMembers, T))
    {
        alias memberType = typeof(__traits(getMember, item, member));
        enum isMemberVariable = is(typeof(() {__traits(getMember, item, member) = __traits(getMember, item, member).init; }));
        //static if(is(memberType == struct)) pragma(msg, T, ".", member, " is struct");
        //static if(isDynamicArray!memberType && is(ElementType!memberType == struct)) pragma(msg, T, ".", member, " is struct array");

        static if(isMemberVariable)
        {
            auto include = true;
            foreach(attr; __traits(getAttributes, __traits(getMember, item, member)))
            {
                enum idx = staticIndexOf!(attr, __traits(getAttributes, __traits(getMember, item, member)));
                static if(isCondition!(typeof(attr)))
                {
                    //check condition
                    auto attribute = mixin(`__traits(getAttributes, T.` ~ member ~ `)`)[idx];
                    if(!attribute.cond(item))
                    {
                        include = false;
                        continue;
                    }
                }
            }

            if(include)
            {
                //debug writeln("processing ", member);
                memberCallback(__traits(getMember, item, member));
            }
        }
    }
}

/// Serialize given Mqtt packet
void serialize(W, T)(ref W wtr, ref T item) if (isMqttPacket!T && is(W == Writer!Out, Out))
{
    static assert(hasFixedHeader!T, format("'%s' packet has no required header field!", T.stringof));

    //set remaining packet length by checking packet conditions
    int len;
    item.processMembers!(a => len += a.itemLength);
    item.header.length = len;

    //check if is valid
    try item.validate();
    catch (Exception ex) 
        throw new PacketFormatException(format("'%s' packet is not valid: %s", T.stringof, ex.msg), ex);

    //write members to output writer
    item.processMembers!((ref a) => wtr.write(a));
}

